name: Translate README

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # ISO Langusge Codes: https://cloud.google.com/translate/docs/languages  
      - name: Adding README - Persian
        uses: dephraiim/translate-readme@main
        with:
          LANG: fa
      - name: Adding README - English
        uses: dephraiim/translate-readme@main
        with:
          LANG: en